// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: endorsement.proto

package org.iotexproject.antenna.grpc.type;

public final class EndorsementOuterClass {
  private EndorsementOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EndorsementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.iotexproject.antenna.grpc.type.Endorsement)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 height = 1;</code>
     */
    long getHeight();

    /**
     * <code>uint32 round = 2;</code>
     */
    int getRound();

    /**
     * <code>bytes blockHash = 3;</code>
     */
    com.google.protobuf.ByteString getBlockHash();

    /**
     * <code>.org.iotexproject.antenna.grpc.type.Endorsement.ConsensusVoteTopic topic = 4;</code>
     */
    int getTopicValue();
    /**
     * <code>.org.iotexproject.antenna.grpc.type.Endorsement.ConsensusVoteTopic topic = 4;</code>
     */
    org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.ConsensusVoteTopic getTopic();

    /**
     * <code>string endorser = 5;</code>
     */
    java.lang.String getEndorser();
    /**
     * <code>string endorser = 5;</code>
     */
    com.google.protobuf.ByteString
        getEndorserBytes();

    /**
     * <code>bytes endorserPubKey = 6;</code>
     */
    com.google.protobuf.ByteString getEndorserPubKey();

    /**
     * <code>bool decision = 7;</code>
     */
    boolean getDecision();

    /**
     * <code>bytes signature = 8;</code>
     */
    com.google.protobuf.ByteString getSignature();
  }
  /**
   * <pre>
   * corresponding to prepare and pre-prepare phase in view change protocol
   * </pre>
   *
   * Protobuf type {@code org.iotexproject.antenna.grpc.type.Endorsement}
   */
  public  static final class Endorsement extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.iotexproject.antenna.grpc.type.Endorsement)
      EndorsementOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Endorsement.newBuilder() to construct.
    private Endorsement(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Endorsement() {
      blockHash_ = com.google.protobuf.ByteString.EMPTY;
      topic_ = 0;
      endorser_ = "";
      endorserPubKey_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Endorsement(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              height_ = input.readUInt64();
              break;
            }
            case 16: {

              round_ = input.readUInt32();
              break;
            }
            case 26: {

              blockHash_ = input.readBytes();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              topic_ = rawValue;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              endorser_ = s;
              break;
            }
            case 50: {

              endorserPubKey_ = input.readBytes();
              break;
            }
            case 56: {

              decision_ = input.readBool();
              break;
            }
            case 66: {

              signature_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.iotexproject.antenna.grpc.type.EndorsementOuterClass.internal_static_org_iotexproject_antenna_grpc_type_Endorsement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.iotexproject.antenna.grpc.type.EndorsementOuterClass.internal_static_org_iotexproject_antenna_grpc_type_Endorsement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.class, org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.Builder.class);
    }

    /**
     * Protobuf enum {@code org.iotexproject.antenna.grpc.type.Endorsement.ConsensusVoteTopic}
     */
    public enum ConsensusVoteTopic
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PROPOSAL = 0;</code>
       */
      PROPOSAL(0),
      /**
       * <code>LOCK = 1;</code>
       */
      LOCK(1),
      /**
       * <code>COMMIT = 2;</code>
       */
      COMMIT(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>PROPOSAL = 0;</code>
       */
      public static final int PROPOSAL_VALUE = 0;
      /**
       * <code>LOCK = 1;</code>
       */
      public static final int LOCK_VALUE = 1;
      /**
       * <code>COMMIT = 2;</code>
       */
      public static final int COMMIT_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ConsensusVoteTopic valueOf(int value) {
        return forNumber(value);
      }

      public static ConsensusVoteTopic forNumber(int value) {
        switch (value) {
          case 0: return PROPOSAL;
          case 1: return LOCK;
          case 2: return COMMIT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ConsensusVoteTopic>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ConsensusVoteTopic> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ConsensusVoteTopic>() {
              public ConsensusVoteTopic findValueByNumber(int number) {
                return ConsensusVoteTopic.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.getDescriptor().getEnumTypes().get(0);
      }

      private static final ConsensusVoteTopic[] VALUES = values();

      public static ConsensusVoteTopic valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ConsensusVoteTopic(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.iotexproject.antenna.grpc.type.Endorsement.ConsensusVoteTopic)
    }

    public static final int HEIGHT_FIELD_NUMBER = 1;
    private long height_;
    /**
     * <code>uint64 height = 1;</code>
     */
    public long getHeight() {
      return height_;
    }

    public static final int ROUND_FIELD_NUMBER = 2;
    private int round_;
    /**
     * <code>uint32 round = 2;</code>
     */
    public int getRound() {
      return round_;
    }

    public static final int BLOCKHASH_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString blockHash_;
    /**
     * <code>bytes blockHash = 3;</code>
     */
    public com.google.protobuf.ByteString getBlockHash() {
      return blockHash_;
    }

    public static final int TOPIC_FIELD_NUMBER = 4;
    private int topic_;
    /**
     * <code>.org.iotexproject.antenna.grpc.type.Endorsement.ConsensusVoteTopic topic = 4;</code>
     */
    public int getTopicValue() {
      return topic_;
    }
    /**
     * <code>.org.iotexproject.antenna.grpc.type.Endorsement.ConsensusVoteTopic topic = 4;</code>
     */
    public org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.ConsensusVoteTopic getTopic() {
      @SuppressWarnings("deprecation")
      org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.ConsensusVoteTopic result = org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.ConsensusVoteTopic.valueOf(topic_);
      return result == null ? org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.ConsensusVoteTopic.UNRECOGNIZED : result;
    }

    public static final int ENDORSER_FIELD_NUMBER = 5;
    private volatile java.lang.Object endorser_;
    /**
     * <code>string endorser = 5;</code>
     */
    public java.lang.String getEndorser() {
      java.lang.Object ref = endorser_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endorser_ = s;
        return s;
      }
    }
    /**
     * <code>string endorser = 5;</code>
     */
    public com.google.protobuf.ByteString
        getEndorserBytes() {
      java.lang.Object ref = endorser_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endorser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDORSERPUBKEY_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString endorserPubKey_;
    /**
     * <code>bytes endorserPubKey = 6;</code>
     */
    public com.google.protobuf.ByteString getEndorserPubKey() {
      return endorserPubKey_;
    }

    public static final int DECISION_FIELD_NUMBER = 7;
    private boolean decision_;
    /**
     * <code>bool decision = 7;</code>
     */
    public boolean getDecision() {
      return decision_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>bytes signature = 8;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (height_ != 0L) {
        output.writeUInt64(1, height_);
      }
      if (round_ != 0) {
        output.writeUInt32(2, round_);
      }
      if (!blockHash_.isEmpty()) {
        output.writeBytes(3, blockHash_);
      }
      if (topic_ != org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.ConsensusVoteTopic.PROPOSAL.getNumber()) {
        output.writeEnum(4, topic_);
      }
      if (!getEndorserBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, endorser_);
      }
      if (!endorserPubKey_.isEmpty()) {
        output.writeBytes(6, endorserPubKey_);
      }
      if (decision_ != false) {
        output.writeBool(7, decision_);
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(8, signature_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (height_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, height_);
      }
      if (round_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, round_);
      }
      if (!blockHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, blockHash_);
      }
      if (topic_ != org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.ConsensusVoteTopic.PROPOSAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, topic_);
      }
      if (!getEndorserBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, endorser_);
      }
      if (!endorserPubKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, endorserPubKey_);
      }
      if (decision_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, decision_);
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, signature_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement)) {
        return super.equals(obj);
      }
      org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement other = (org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement) obj;

      if (getHeight()
          != other.getHeight()) return false;
      if (getRound()
          != other.getRound()) return false;
      if (!getBlockHash()
          .equals(other.getBlockHash())) return false;
      if (topic_ != other.topic_) return false;
      if (!getEndorser()
          .equals(other.getEndorser())) return false;
      if (!getEndorserPubKey()
          .equals(other.getEndorserPubKey())) return false;
      if (getDecision()
          != other.getDecision()) return false;
      if (!getSignature()
          .equals(other.getSignature())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHeight());
      hash = (37 * hash) + ROUND_FIELD_NUMBER;
      hash = (53 * hash) + getRound();
      hash = (37 * hash) + BLOCKHASH_FIELD_NUMBER;
      hash = (53 * hash) + getBlockHash().hashCode();
      hash = (37 * hash) + TOPIC_FIELD_NUMBER;
      hash = (53 * hash) + topic_;
      hash = (37 * hash) + ENDORSER_FIELD_NUMBER;
      hash = (53 * hash) + getEndorser().hashCode();
      hash = (37 * hash) + ENDORSERPUBKEY_FIELD_NUMBER;
      hash = (53 * hash) + getEndorserPubKey().hashCode();
      hash = (37 * hash) + DECISION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDecision());
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * corresponding to prepare and pre-prepare phase in view change protocol
     * </pre>
     *
     * Protobuf type {@code org.iotexproject.antenna.grpc.type.Endorsement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.iotexproject.antenna.grpc.type.Endorsement)
        org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.iotexproject.antenna.grpc.type.EndorsementOuterClass.internal_static_org_iotexproject_antenna_grpc_type_Endorsement_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.iotexproject.antenna.grpc.type.EndorsementOuterClass.internal_static_org_iotexproject_antenna_grpc_type_Endorsement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.class, org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.Builder.class);
      }

      // Construct using org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        height_ = 0L;

        round_ = 0;

        blockHash_ = com.google.protobuf.ByteString.EMPTY;

        topic_ = 0;

        endorser_ = "";

        endorserPubKey_ = com.google.protobuf.ByteString.EMPTY;

        decision_ = false;

        signature_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.iotexproject.antenna.grpc.type.EndorsementOuterClass.internal_static_org_iotexproject_antenna_grpc_type_Endorsement_descriptor;
      }

      @java.lang.Override
      public org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement getDefaultInstanceForType() {
        return org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.getDefaultInstance();
      }

      @java.lang.Override
      public org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement build() {
        org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement buildPartial() {
        org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement result = new org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement(this);
        result.height_ = height_;
        result.round_ = round_;
        result.blockHash_ = blockHash_;
        result.topic_ = topic_;
        result.endorser_ = endorser_;
        result.endorserPubKey_ = endorserPubKey_;
        result.decision_ = decision_;
        result.signature_ = signature_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement) {
          return mergeFrom((org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement other) {
        if (other == org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.getDefaultInstance()) return this;
        if (other.getHeight() != 0L) {
          setHeight(other.getHeight());
        }
        if (other.getRound() != 0) {
          setRound(other.getRound());
        }
        if (other.getBlockHash() != com.google.protobuf.ByteString.EMPTY) {
          setBlockHash(other.getBlockHash());
        }
        if (other.topic_ != 0) {
          setTopicValue(other.getTopicValue());
        }
        if (!other.getEndorser().isEmpty()) {
          endorser_ = other.endorser_;
          onChanged();
        }
        if (other.getEndorserPubKey() != com.google.protobuf.ByteString.EMPTY) {
          setEndorserPubKey(other.getEndorserPubKey());
        }
        if (other.getDecision() != false) {
          setDecision(other.getDecision());
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long height_ ;
      /**
       * <code>uint64 height = 1;</code>
       */
      public long getHeight() {
        return height_;
      }
      /**
       * <code>uint64 height = 1;</code>
       */
      public Builder setHeight(long value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 height = 1;</code>
       */
      public Builder clearHeight() {
        
        height_ = 0L;
        onChanged();
        return this;
      }

      private int round_ ;
      /**
       * <code>uint32 round = 2;</code>
       */
      public int getRound() {
        return round_;
      }
      /**
       * <code>uint32 round = 2;</code>
       */
      public Builder setRound(int value) {
        
        round_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 round = 2;</code>
       */
      public Builder clearRound() {
        
        round_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString blockHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes blockHash = 3;</code>
       */
      public com.google.protobuf.ByteString getBlockHash() {
        return blockHash_;
      }
      /**
       * <code>bytes blockHash = 3;</code>
       */
      public Builder setBlockHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        blockHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes blockHash = 3;</code>
       */
      public Builder clearBlockHash() {
        
        blockHash_ = getDefaultInstance().getBlockHash();
        onChanged();
        return this;
      }

      private int topic_ = 0;
      /**
       * <code>.org.iotexproject.antenna.grpc.type.Endorsement.ConsensusVoteTopic topic = 4;</code>
       */
      public int getTopicValue() {
        return topic_;
      }
      /**
       * <code>.org.iotexproject.antenna.grpc.type.Endorsement.ConsensusVoteTopic topic = 4;</code>
       */
      public Builder setTopicValue(int value) {
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.org.iotexproject.antenna.grpc.type.Endorsement.ConsensusVoteTopic topic = 4;</code>
       */
      public org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.ConsensusVoteTopic getTopic() {
        @SuppressWarnings("deprecation")
        org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.ConsensusVoteTopic result = org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.ConsensusVoteTopic.valueOf(topic_);
        return result == null ? org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.ConsensusVoteTopic.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.iotexproject.antenna.grpc.type.Endorsement.ConsensusVoteTopic topic = 4;</code>
       */
      public Builder setTopic(org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.ConsensusVoteTopic value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        topic_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.iotexproject.antenna.grpc.type.Endorsement.ConsensusVoteTopic topic = 4;</code>
       */
      public Builder clearTopic() {
        
        topic_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object endorser_ = "";
      /**
       * <code>string endorser = 5;</code>
       */
      public java.lang.String getEndorser() {
        java.lang.Object ref = endorser_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          endorser_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string endorser = 5;</code>
       */
      public com.google.protobuf.ByteString
          getEndorserBytes() {
        java.lang.Object ref = endorser_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endorser_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string endorser = 5;</code>
       */
      public Builder setEndorser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        endorser_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string endorser = 5;</code>
       */
      public Builder clearEndorser() {
        
        endorser_ = getDefaultInstance().getEndorser();
        onChanged();
        return this;
      }
      /**
       * <code>string endorser = 5;</code>
       */
      public Builder setEndorserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        endorser_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString endorserPubKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes endorserPubKey = 6;</code>
       */
      public com.google.protobuf.ByteString getEndorserPubKey() {
        return endorserPubKey_;
      }
      /**
       * <code>bytes endorserPubKey = 6;</code>
       */
      public Builder setEndorserPubKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        endorserPubKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes endorserPubKey = 6;</code>
       */
      public Builder clearEndorserPubKey() {
        
        endorserPubKey_ = getDefaultInstance().getEndorserPubKey();
        onChanged();
        return this;
      }

      private boolean decision_ ;
      /**
       * <code>bool decision = 7;</code>
       */
      public boolean getDecision() {
        return decision_;
      }
      /**
       * <code>bool decision = 7;</code>
       */
      public Builder setDecision(boolean value) {
        
        decision_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool decision = 7;</code>
       */
      public Builder clearDecision() {
        
        decision_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes signature = 8;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>bytes signature = 8;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes signature = 8;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.iotexproject.antenna.grpc.type.Endorsement)
    }

    // @@protoc_insertion_point(class_scope:org.iotexproject.antenna.grpc.type.Endorsement)
    private static final org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement();
    }

    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Endorsement>
        PARSER = new com.google.protobuf.AbstractParser<Endorsement>() {
      @java.lang.Override
      public Endorsement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Endorsement(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Endorsement> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Endorsement> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EndorsementSetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.iotexproject.antenna.grpc.type.EndorsementSet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes blockHash = 1;</code>
     */
    com.google.protobuf.ByteString getBlockHash();

    /**
     * <code>uint32 round = 2;</code>
     */
    int getRound();

    /**
     * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
     */
    java.util.List<org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement> 
        getEndorsementsList();
    /**
     * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
     */
    org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement getEndorsements(int index);
    /**
     * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
     */
    int getEndorsementsCount();
    /**
     * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
     */
    java.util.List<? extends org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementOrBuilder> 
        getEndorsementsOrBuilderList();
    /**
     * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
     */
    org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementOrBuilder getEndorsementsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.iotexproject.antenna.grpc.type.EndorsementSet}
   */
  public  static final class EndorsementSet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.iotexproject.antenna.grpc.type.EndorsementSet)
      EndorsementSetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EndorsementSet.newBuilder() to construct.
    private EndorsementSet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EndorsementSet() {
      blockHash_ = com.google.protobuf.ByteString.EMPTY;
      endorsements_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EndorsementSet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              blockHash_ = input.readBytes();
              break;
            }
            case 16: {

              round_ = input.readUInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                endorsements_ = new java.util.ArrayList<org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement>();
                mutable_bitField0_ |= 0x00000004;
              }
              endorsements_.add(
                  input.readMessage(org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          endorsements_ = java.util.Collections.unmodifiableList(endorsements_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.iotexproject.antenna.grpc.type.EndorsementOuterClass.internal_static_org_iotexproject_antenna_grpc_type_EndorsementSet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.iotexproject.antenna.grpc.type.EndorsementOuterClass.internal_static_org_iotexproject_antenna_grpc_type_EndorsementSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet.class, org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet.Builder.class);
    }

    private int bitField0_;
    public static final int BLOCKHASH_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString blockHash_;
    /**
     * <code>bytes blockHash = 1;</code>
     */
    public com.google.protobuf.ByteString getBlockHash() {
      return blockHash_;
    }

    public static final int ROUND_FIELD_NUMBER = 2;
    private int round_;
    /**
     * <code>uint32 round = 2;</code>
     */
    public int getRound() {
      return round_;
    }

    public static final int ENDORSEMENTS_FIELD_NUMBER = 3;
    private java.util.List<org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement> endorsements_;
    /**
     * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
     */
    public java.util.List<org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement> getEndorsementsList() {
      return endorsements_;
    }
    /**
     * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
     */
    public java.util.List<? extends org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementOrBuilder> 
        getEndorsementsOrBuilderList() {
      return endorsements_;
    }
    /**
     * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
     */
    public int getEndorsementsCount() {
      return endorsements_.size();
    }
    /**
     * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
     */
    public org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement getEndorsements(int index) {
      return endorsements_.get(index);
    }
    /**
     * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
     */
    public org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementOrBuilder getEndorsementsOrBuilder(
        int index) {
      return endorsements_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!blockHash_.isEmpty()) {
        output.writeBytes(1, blockHash_);
      }
      if (round_ != 0) {
        output.writeUInt32(2, round_);
      }
      for (int i = 0; i < endorsements_.size(); i++) {
        output.writeMessage(3, endorsements_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!blockHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, blockHash_);
      }
      if (round_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, round_);
      }
      for (int i = 0; i < endorsements_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, endorsements_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet)) {
        return super.equals(obj);
      }
      org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet other = (org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet) obj;

      if (!getBlockHash()
          .equals(other.getBlockHash())) return false;
      if (getRound()
          != other.getRound()) return false;
      if (!getEndorsementsList()
          .equals(other.getEndorsementsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BLOCKHASH_FIELD_NUMBER;
      hash = (53 * hash) + getBlockHash().hashCode();
      hash = (37 * hash) + ROUND_FIELD_NUMBER;
      hash = (53 * hash) + getRound();
      if (getEndorsementsCount() > 0) {
        hash = (37 * hash) + ENDORSEMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getEndorsementsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.iotexproject.antenna.grpc.type.EndorsementSet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.iotexproject.antenna.grpc.type.EndorsementSet)
        org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.iotexproject.antenna.grpc.type.EndorsementOuterClass.internal_static_org_iotexproject_antenna_grpc_type_EndorsementSet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.iotexproject.antenna.grpc.type.EndorsementOuterClass.internal_static_org_iotexproject_antenna_grpc_type_EndorsementSet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet.class, org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet.Builder.class);
      }

      // Construct using org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEndorsementsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        blockHash_ = com.google.protobuf.ByteString.EMPTY;

        round_ = 0;

        if (endorsementsBuilder_ == null) {
          endorsements_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          endorsementsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.iotexproject.antenna.grpc.type.EndorsementOuterClass.internal_static_org_iotexproject_antenna_grpc_type_EndorsementSet_descriptor;
      }

      @java.lang.Override
      public org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet getDefaultInstanceForType() {
        return org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet.getDefaultInstance();
      }

      @java.lang.Override
      public org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet build() {
        org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet buildPartial() {
        org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet result = new org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.blockHash_ = blockHash_;
        result.round_ = round_;
        if (endorsementsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            endorsements_ = java.util.Collections.unmodifiableList(endorsements_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.endorsements_ = endorsements_;
        } else {
          result.endorsements_ = endorsementsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet) {
          return mergeFrom((org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet other) {
        if (other == org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet.getDefaultInstance()) return this;
        if (other.getBlockHash() != com.google.protobuf.ByteString.EMPTY) {
          setBlockHash(other.getBlockHash());
        }
        if (other.getRound() != 0) {
          setRound(other.getRound());
        }
        if (endorsementsBuilder_ == null) {
          if (!other.endorsements_.isEmpty()) {
            if (endorsements_.isEmpty()) {
              endorsements_ = other.endorsements_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureEndorsementsIsMutable();
              endorsements_.addAll(other.endorsements_);
            }
            onChanged();
          }
        } else {
          if (!other.endorsements_.isEmpty()) {
            if (endorsementsBuilder_.isEmpty()) {
              endorsementsBuilder_.dispose();
              endorsementsBuilder_ = null;
              endorsements_ = other.endorsements_;
              bitField0_ = (bitField0_ & ~0x00000004);
              endorsementsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEndorsementsFieldBuilder() : null;
            } else {
              endorsementsBuilder_.addAllMessages(other.endorsements_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString blockHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes blockHash = 1;</code>
       */
      public com.google.protobuf.ByteString getBlockHash() {
        return blockHash_;
      }
      /**
       * <code>bytes blockHash = 1;</code>
       */
      public Builder setBlockHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        blockHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes blockHash = 1;</code>
       */
      public Builder clearBlockHash() {
        
        blockHash_ = getDefaultInstance().getBlockHash();
        onChanged();
        return this;
      }

      private int round_ ;
      /**
       * <code>uint32 round = 2;</code>
       */
      public int getRound() {
        return round_;
      }
      /**
       * <code>uint32 round = 2;</code>
       */
      public Builder setRound(int value) {
        
        round_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 round = 2;</code>
       */
      public Builder clearRound() {
        
        round_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement> endorsements_ =
        java.util.Collections.emptyList();
      private void ensureEndorsementsIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          endorsements_ = new java.util.ArrayList<org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement>(endorsements_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement, org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.Builder, org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementOrBuilder> endorsementsBuilder_;

      /**
       * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
       */
      public java.util.List<org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement> getEndorsementsList() {
        if (endorsementsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(endorsements_);
        } else {
          return endorsementsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
       */
      public int getEndorsementsCount() {
        if (endorsementsBuilder_ == null) {
          return endorsements_.size();
        } else {
          return endorsementsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
       */
      public org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement getEndorsements(int index) {
        if (endorsementsBuilder_ == null) {
          return endorsements_.get(index);
        } else {
          return endorsementsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
       */
      public Builder setEndorsements(
          int index, org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement value) {
        if (endorsementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEndorsementsIsMutable();
          endorsements_.set(index, value);
          onChanged();
        } else {
          endorsementsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
       */
      public Builder setEndorsements(
          int index, org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.Builder builderForValue) {
        if (endorsementsBuilder_ == null) {
          ensureEndorsementsIsMutable();
          endorsements_.set(index, builderForValue.build());
          onChanged();
        } else {
          endorsementsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
       */
      public Builder addEndorsements(org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement value) {
        if (endorsementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEndorsementsIsMutable();
          endorsements_.add(value);
          onChanged();
        } else {
          endorsementsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
       */
      public Builder addEndorsements(
          int index, org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement value) {
        if (endorsementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEndorsementsIsMutable();
          endorsements_.add(index, value);
          onChanged();
        } else {
          endorsementsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
       */
      public Builder addEndorsements(
          org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.Builder builderForValue) {
        if (endorsementsBuilder_ == null) {
          ensureEndorsementsIsMutable();
          endorsements_.add(builderForValue.build());
          onChanged();
        } else {
          endorsementsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
       */
      public Builder addEndorsements(
          int index, org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.Builder builderForValue) {
        if (endorsementsBuilder_ == null) {
          ensureEndorsementsIsMutable();
          endorsements_.add(index, builderForValue.build());
          onChanged();
        } else {
          endorsementsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
       */
      public Builder addAllEndorsements(
          java.lang.Iterable<? extends org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement> values) {
        if (endorsementsBuilder_ == null) {
          ensureEndorsementsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, endorsements_);
          onChanged();
        } else {
          endorsementsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
       */
      public Builder clearEndorsements() {
        if (endorsementsBuilder_ == null) {
          endorsements_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          endorsementsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
       */
      public Builder removeEndorsements(int index) {
        if (endorsementsBuilder_ == null) {
          ensureEndorsementsIsMutable();
          endorsements_.remove(index);
          onChanged();
        } else {
          endorsementsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
       */
      public org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.Builder getEndorsementsBuilder(
          int index) {
        return getEndorsementsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
       */
      public org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementOrBuilder getEndorsementsOrBuilder(
          int index) {
        if (endorsementsBuilder_ == null) {
          return endorsements_.get(index);  } else {
          return endorsementsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
       */
      public java.util.List<? extends org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementOrBuilder> 
           getEndorsementsOrBuilderList() {
        if (endorsementsBuilder_ != null) {
          return endorsementsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(endorsements_);
        }
      }
      /**
       * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
       */
      public org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.Builder addEndorsementsBuilder() {
        return getEndorsementsFieldBuilder().addBuilder(
            org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.getDefaultInstance());
      }
      /**
       * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
       */
      public org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.Builder addEndorsementsBuilder(
          int index) {
        return getEndorsementsFieldBuilder().addBuilder(
            index, org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.getDefaultInstance());
      }
      /**
       * <code>repeated .org.iotexproject.antenna.grpc.type.Endorsement endorsements = 3;</code>
       */
      public java.util.List<org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.Builder> 
           getEndorsementsBuilderList() {
        return getEndorsementsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement, org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.Builder, org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementOrBuilder> 
          getEndorsementsFieldBuilder() {
        if (endorsementsBuilder_ == null) {
          endorsementsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement, org.iotexproject.antenna.grpc.type.EndorsementOuterClass.Endorsement.Builder, org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementOrBuilder>(
                  endorsements_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          endorsements_ = null;
        }
        return endorsementsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.iotexproject.antenna.grpc.type.EndorsementSet)
    }

    // @@protoc_insertion_point(class_scope:org.iotexproject.antenna.grpc.type.EndorsementSet)
    private static final org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet();
    }

    public static org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EndorsementSet>
        PARSER = new com.google.protobuf.AbstractParser<EndorsementSet>() {
      @java.lang.Override
      public EndorsementSet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EndorsementSet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EndorsementSet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EndorsementSet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.iotexproject.antenna.grpc.type.EndorsementOuterClass.EndorsementSet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_iotexproject_antenna_grpc_type_Endorsement_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_iotexproject_antenna_grpc_type_Endorsement_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_iotexproject_antenna_grpc_type_EndorsementSet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_iotexproject_antenna_grpc_type_EndorsementSet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021endorsement.proto\022\"org.iotexproject.an" +
      "tenna.grpc.type\"\233\002\n\013Endorsement\022\016\n\006heigh" +
      "t\030\001 \001(\004\022\r\n\005round\030\002 \001(\r\022\021\n\tblockHash\030\003 \001(" +
      "\014\022Q\n\005topic\030\004 \001(\0162B.org.iotexproject.ante" +
      "nna.grpc.type.Endorsement.ConsensusVoteT" +
      "opic\022\020\n\010endorser\030\005 \001(\t\022\026\n\016endorserPubKey" +
      "\030\006 \001(\014\022\020\n\010decision\030\007 \001(\010\022\021\n\tsignature\030\010 " +
      "\001(\014\"8\n\022ConsensusVoteTopic\022\014\n\010PROPOSAL\020\000\022" +
      "\010\n\004LOCK\020\001\022\n\n\006COMMIT\020\002\"y\n\016EndorsementSet\022" +
      "\021\n\tblockHash\030\001 \001(\014\022\r\n\005round\030\002 \001(\r\022E\n\014end" +
      "orsements\030\003 \003(\0132/.org.iotexproject.anten" +
      "na.grpc.type.Endorsementb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_iotexproject_antenna_grpc_type_Endorsement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_iotexproject_antenna_grpc_type_Endorsement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_iotexproject_antenna_grpc_type_Endorsement_descriptor,
        new java.lang.String[] { "Height", "Round", "BlockHash", "Topic", "Endorser", "EndorserPubKey", "Decision", "Signature", });
    internal_static_org_iotexproject_antenna_grpc_type_EndorsementSet_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_iotexproject_antenna_grpc_type_EndorsementSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_iotexproject_antenna_grpc_type_EndorsementSet_descriptor,
        new java.lang.String[] { "BlockHash", "Round", "Endorsements", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
