// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package org.iotexproject.antenna.grpc.account;

public final class AccountOuterClass {
  private AccountOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AccountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.iotexproject.antenna.grpc.account.Account)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * used by state-based model
     * </pre>
     *
     * <code>uint64 nonce = 1;</code>
     */
    long getNonce();

    /**
     * <code>string balance = 2;</code>
     */
    java.lang.String getBalance();
    /**
     * <code>string balance = 2;</code>
     */
    com.google.protobuf.ByteString
        getBalanceBytes();

    /**
     * <code>bytes root = 3;</code>
     */
    com.google.protobuf.ByteString getRoot();

    /**
     * <code>bytes codeHash = 4;</code>
     */
    com.google.protobuf.ByteString getCodeHash();

    /**
     * <code>bool isCandidate = 5;</code>
     */
    boolean getIsCandidate();

    /**
     * <code>bytes votingWeight = 6;</code>
     */
    com.google.protobuf.ByteString getVotingWeight();

    /**
     * <code>string votee = 7;</code>
     */
    java.lang.String getVotee();
    /**
     * <code>string votee = 7;</code>
     */
    com.google.protobuf.ByteString
        getVoteeBytes();
  }
  /**
   * Protobuf type {@code org.iotexproject.antenna.grpc.account.Account}
   */
  public  static final class Account extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.iotexproject.antenna.grpc.account.Account)
      AccountOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Account.newBuilder() to construct.
    private Account(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Account() {
      balance_ = "";
      root_ = com.google.protobuf.ByteString.EMPTY;
      codeHash_ = com.google.protobuf.ByteString.EMPTY;
      votingWeight_ = com.google.protobuf.ByteString.EMPTY;
      votee_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Account(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              nonce_ = input.readUInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              balance_ = s;
              break;
            }
            case 26: {

              root_ = input.readBytes();
              break;
            }
            case 34: {

              codeHash_ = input.readBytes();
              break;
            }
            case 40: {

              isCandidate_ = input.readBool();
              break;
            }
            case 50: {

              votingWeight_ = input.readBytes();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              votee_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.iotexproject.antenna.grpc.account.AccountOuterClass.internal_static_org_iotexproject_antenna_grpc_account_Account_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.iotexproject.antenna.grpc.account.AccountOuterClass.internal_static_org_iotexproject_antenna_grpc_account_Account_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.iotexproject.antenna.grpc.account.AccountOuterClass.Account.class, org.iotexproject.antenna.grpc.account.AccountOuterClass.Account.Builder.class);
    }

    public static final int NONCE_FIELD_NUMBER = 1;
    private long nonce_;
    /**
     * <pre>
     * used by state-based model
     * </pre>
     *
     * <code>uint64 nonce = 1;</code>
     */
    public long getNonce() {
      return nonce_;
    }

    public static final int BALANCE_FIELD_NUMBER = 2;
    private volatile java.lang.Object balance_;
    /**
     * <code>string balance = 2;</code>
     */
    public java.lang.String getBalance() {
      java.lang.Object ref = balance_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        balance_ = s;
        return s;
      }
    }
    /**
     * <code>string balance = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBalanceBytes() {
      java.lang.Object ref = balance_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        balance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROOT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString root_;
    /**
     * <code>bytes root = 3;</code>
     */
    public com.google.protobuf.ByteString getRoot() {
      return root_;
    }

    public static final int CODEHASH_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString codeHash_;
    /**
     * <code>bytes codeHash = 4;</code>
     */
    public com.google.protobuf.ByteString getCodeHash() {
      return codeHash_;
    }

    public static final int ISCANDIDATE_FIELD_NUMBER = 5;
    private boolean isCandidate_;
    /**
     * <code>bool isCandidate = 5;</code>
     */
    public boolean getIsCandidate() {
      return isCandidate_;
    }

    public static final int VOTINGWEIGHT_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString votingWeight_;
    /**
     * <code>bytes votingWeight = 6;</code>
     */
    public com.google.protobuf.ByteString getVotingWeight() {
      return votingWeight_;
    }

    public static final int VOTEE_FIELD_NUMBER = 7;
    private volatile java.lang.Object votee_;
    /**
     * <code>string votee = 7;</code>
     */
    public java.lang.String getVotee() {
      java.lang.Object ref = votee_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        votee_ = s;
        return s;
      }
    }
    /**
     * <code>string votee = 7;</code>
     */
    public com.google.protobuf.ByteString
        getVoteeBytes() {
      java.lang.Object ref = votee_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        votee_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (nonce_ != 0L) {
        output.writeUInt64(1, nonce_);
      }
      if (!getBalanceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, balance_);
      }
      if (!root_.isEmpty()) {
        output.writeBytes(3, root_);
      }
      if (!codeHash_.isEmpty()) {
        output.writeBytes(4, codeHash_);
      }
      if (isCandidate_ != false) {
        output.writeBool(5, isCandidate_);
      }
      if (!votingWeight_.isEmpty()) {
        output.writeBytes(6, votingWeight_);
      }
      if (!getVoteeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, votee_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (nonce_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, nonce_);
      }
      if (!getBalanceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, balance_);
      }
      if (!root_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, root_);
      }
      if (!codeHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, codeHash_);
      }
      if (isCandidate_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isCandidate_);
      }
      if (!votingWeight_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, votingWeight_);
      }
      if (!getVoteeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, votee_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.iotexproject.antenna.grpc.account.AccountOuterClass.Account)) {
        return super.equals(obj);
      }
      org.iotexproject.antenna.grpc.account.AccountOuterClass.Account other = (org.iotexproject.antenna.grpc.account.AccountOuterClass.Account) obj;

      if (getNonce()
          != other.getNonce()) return false;
      if (!getBalance()
          .equals(other.getBalance())) return false;
      if (!getRoot()
          .equals(other.getRoot())) return false;
      if (!getCodeHash()
          .equals(other.getCodeHash())) return false;
      if (getIsCandidate()
          != other.getIsCandidate()) return false;
      if (!getVotingWeight()
          .equals(other.getVotingWeight())) return false;
      if (!getVotee()
          .equals(other.getVotee())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NONCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNonce());
      hash = (37 * hash) + BALANCE_FIELD_NUMBER;
      hash = (53 * hash) + getBalance().hashCode();
      hash = (37 * hash) + ROOT_FIELD_NUMBER;
      hash = (53 * hash) + getRoot().hashCode();
      hash = (37 * hash) + CODEHASH_FIELD_NUMBER;
      hash = (53 * hash) + getCodeHash().hashCode();
      hash = (37 * hash) + ISCANDIDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsCandidate());
      hash = (37 * hash) + VOTINGWEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getVotingWeight().hashCode();
      hash = (37 * hash) + VOTEE_FIELD_NUMBER;
      hash = (53 * hash) + getVotee().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.iotexproject.antenna.grpc.account.AccountOuterClass.Account parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iotexproject.antenna.grpc.account.AccountOuterClass.Account parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.account.AccountOuterClass.Account parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iotexproject.antenna.grpc.account.AccountOuterClass.Account parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.account.AccountOuterClass.Account parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iotexproject.antenna.grpc.account.AccountOuterClass.Account parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.account.AccountOuterClass.Account parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.iotexproject.antenna.grpc.account.AccountOuterClass.Account parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.account.AccountOuterClass.Account parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.iotexproject.antenna.grpc.account.AccountOuterClass.Account parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.account.AccountOuterClass.Account parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.iotexproject.antenna.grpc.account.AccountOuterClass.Account parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.iotexproject.antenna.grpc.account.AccountOuterClass.Account prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.iotexproject.antenna.grpc.account.Account}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.iotexproject.antenna.grpc.account.Account)
        org.iotexproject.antenna.grpc.account.AccountOuterClass.AccountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.iotexproject.antenna.grpc.account.AccountOuterClass.internal_static_org_iotexproject_antenna_grpc_account_Account_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.iotexproject.antenna.grpc.account.AccountOuterClass.internal_static_org_iotexproject_antenna_grpc_account_Account_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.iotexproject.antenna.grpc.account.AccountOuterClass.Account.class, org.iotexproject.antenna.grpc.account.AccountOuterClass.Account.Builder.class);
      }

      // Construct using org.iotexproject.antenna.grpc.account.AccountOuterClass.Account.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nonce_ = 0L;

        balance_ = "";

        root_ = com.google.protobuf.ByteString.EMPTY;

        codeHash_ = com.google.protobuf.ByteString.EMPTY;

        isCandidate_ = false;

        votingWeight_ = com.google.protobuf.ByteString.EMPTY;

        votee_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.iotexproject.antenna.grpc.account.AccountOuterClass.internal_static_org_iotexproject_antenna_grpc_account_Account_descriptor;
      }

      @java.lang.Override
      public org.iotexproject.antenna.grpc.account.AccountOuterClass.Account getDefaultInstanceForType() {
        return org.iotexproject.antenna.grpc.account.AccountOuterClass.Account.getDefaultInstance();
      }

      @java.lang.Override
      public org.iotexproject.antenna.grpc.account.AccountOuterClass.Account build() {
        org.iotexproject.antenna.grpc.account.AccountOuterClass.Account result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.iotexproject.antenna.grpc.account.AccountOuterClass.Account buildPartial() {
        org.iotexproject.antenna.grpc.account.AccountOuterClass.Account result = new org.iotexproject.antenna.grpc.account.AccountOuterClass.Account(this);
        result.nonce_ = nonce_;
        result.balance_ = balance_;
        result.root_ = root_;
        result.codeHash_ = codeHash_;
        result.isCandidate_ = isCandidate_;
        result.votingWeight_ = votingWeight_;
        result.votee_ = votee_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.iotexproject.antenna.grpc.account.AccountOuterClass.Account) {
          return mergeFrom((org.iotexproject.antenna.grpc.account.AccountOuterClass.Account)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.iotexproject.antenna.grpc.account.AccountOuterClass.Account other) {
        if (other == org.iotexproject.antenna.grpc.account.AccountOuterClass.Account.getDefaultInstance()) return this;
        if (other.getNonce() != 0L) {
          setNonce(other.getNonce());
        }
        if (!other.getBalance().isEmpty()) {
          balance_ = other.balance_;
          onChanged();
        }
        if (other.getRoot() != com.google.protobuf.ByteString.EMPTY) {
          setRoot(other.getRoot());
        }
        if (other.getCodeHash() != com.google.protobuf.ByteString.EMPTY) {
          setCodeHash(other.getCodeHash());
        }
        if (other.getIsCandidate() != false) {
          setIsCandidate(other.getIsCandidate());
        }
        if (other.getVotingWeight() != com.google.protobuf.ByteString.EMPTY) {
          setVotingWeight(other.getVotingWeight());
        }
        if (!other.getVotee().isEmpty()) {
          votee_ = other.votee_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.iotexproject.antenna.grpc.account.AccountOuterClass.Account parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.iotexproject.antenna.grpc.account.AccountOuterClass.Account) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long nonce_ ;
      /**
       * <pre>
       * used by state-based model
       * </pre>
       *
       * <code>uint64 nonce = 1;</code>
       */
      public long getNonce() {
        return nonce_;
      }
      /**
       * <pre>
       * used by state-based model
       * </pre>
       *
       * <code>uint64 nonce = 1;</code>
       */
      public Builder setNonce(long value) {
        
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * used by state-based model
       * </pre>
       *
       * <code>uint64 nonce = 1;</code>
       */
      public Builder clearNonce() {
        
        nonce_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object balance_ = "";
      /**
       * <code>string balance = 2;</code>
       */
      public java.lang.String getBalance() {
        java.lang.Object ref = balance_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          balance_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string balance = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBalanceBytes() {
        java.lang.Object ref = balance_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          balance_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string balance = 2;</code>
       */
      public Builder setBalance(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        balance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string balance = 2;</code>
       */
      public Builder clearBalance() {
        
        balance_ = getDefaultInstance().getBalance();
        onChanged();
        return this;
      }
      /**
       * <code>string balance = 2;</code>
       */
      public Builder setBalanceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        balance_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString root_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes root = 3;</code>
       */
      public com.google.protobuf.ByteString getRoot() {
        return root_;
      }
      /**
       * <code>bytes root = 3;</code>
       */
      public Builder setRoot(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        root_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes root = 3;</code>
       */
      public Builder clearRoot() {
        
        root_ = getDefaultInstance().getRoot();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString codeHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes codeHash = 4;</code>
       */
      public com.google.protobuf.ByteString getCodeHash() {
        return codeHash_;
      }
      /**
       * <code>bytes codeHash = 4;</code>
       */
      public Builder setCodeHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        codeHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes codeHash = 4;</code>
       */
      public Builder clearCodeHash() {
        
        codeHash_ = getDefaultInstance().getCodeHash();
        onChanged();
        return this;
      }

      private boolean isCandidate_ ;
      /**
       * <code>bool isCandidate = 5;</code>
       */
      public boolean getIsCandidate() {
        return isCandidate_;
      }
      /**
       * <code>bool isCandidate = 5;</code>
       */
      public Builder setIsCandidate(boolean value) {
        
        isCandidate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isCandidate = 5;</code>
       */
      public Builder clearIsCandidate() {
        
        isCandidate_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString votingWeight_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes votingWeight = 6;</code>
       */
      public com.google.protobuf.ByteString getVotingWeight() {
        return votingWeight_;
      }
      /**
       * <code>bytes votingWeight = 6;</code>
       */
      public Builder setVotingWeight(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        votingWeight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes votingWeight = 6;</code>
       */
      public Builder clearVotingWeight() {
        
        votingWeight_ = getDefaultInstance().getVotingWeight();
        onChanged();
        return this;
      }

      private java.lang.Object votee_ = "";
      /**
       * <code>string votee = 7;</code>
       */
      public java.lang.String getVotee() {
        java.lang.Object ref = votee_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          votee_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string votee = 7;</code>
       */
      public com.google.protobuf.ByteString
          getVoteeBytes() {
        java.lang.Object ref = votee_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          votee_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string votee = 7;</code>
       */
      public Builder setVotee(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        votee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string votee = 7;</code>
       */
      public Builder clearVotee() {
        
        votee_ = getDefaultInstance().getVotee();
        onChanged();
        return this;
      }
      /**
       * <code>string votee = 7;</code>
       */
      public Builder setVoteeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        votee_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.iotexproject.antenna.grpc.account.Account)
    }

    // @@protoc_insertion_point(class_scope:org.iotexproject.antenna.grpc.account.Account)
    private static final org.iotexproject.antenna.grpc.account.AccountOuterClass.Account DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.iotexproject.antenna.grpc.account.AccountOuterClass.Account();
    }

    public static org.iotexproject.antenna.grpc.account.AccountOuterClass.Account getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Account>
        PARSER = new com.google.protobuf.AbstractParser<Account>() {
      @java.lang.Override
      public Account parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Account(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Account> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Account> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.iotexproject.antenna.grpc.account.AccountOuterClass.Account getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_iotexproject_antenna_grpc_account_Account_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_iotexproject_antenna_grpc_account_Account_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\raccount.proto\022%org.iotexproject.antenn" +
      "a.grpc.account\"\203\001\n\007Account\022\r\n\005nonce\030\001 \001(" +
      "\004\022\017\n\007balance\030\002 \001(\t\022\014\n\004root\030\003 \001(\014\022\020\n\010code" +
      "Hash\030\004 \001(\014\022\023\n\013isCandidate\030\005 \001(\010\022\024\n\014votin" +
      "gWeight\030\006 \001(\014\022\r\n\005votee\030\007 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_iotexproject_antenna_grpc_account_Account_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_iotexproject_antenna_grpc_account_Account_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_iotexproject_antenna_grpc_account_Account_descriptor,
        new java.lang.String[] { "Nonce", "Balance", "Root", "CodeHash", "IsCandidate", "VotingWeight", "Votee", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
